# Github action to test on push and pull and also notify via slack

name: CI Pipeline

# Trigger workflow on push to main branch and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests
      run: |
        pytest
        
  notify:
    needs: test
    runs-on: ubuntu-latest
    if: always() # Run even if tests fail
    
    steps:
    - name: Notify Slack on Success
      if: needs.test.result == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message
        custom_payload: |
          {
            "attachments": [{
              "color": "#36a64f",
              "text": "✅ Tests passed successfully!\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}",
              "channel": "#ci-notifications"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Notify Slack on Failure
      if: needs.test.result == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,message
        custom_payload: |
          {
            "attachments": [{
              "color": "#D00000",
              "text": "❌ Tests failed!\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nPlease check the workflow run for details.",
              "channel": "#ci-notifications"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}