name: CI Pipeline

# Trigger workflow on push to main branch and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests
      run: |
        pytest
  notify:
    needs: test
    runs-on: ubuntu-latest
    if: always() # Run even if tests fail
    
    steps:
    - name: Notify Slack on Success
      if: needs.test.result == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#ci-notifications'
        message: |
          ✅ Tests passed successfully!
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    - name: Notify Slack on Failure
      if: needs.test.result == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#ci-notifications'
        message: |
          ❌ Tests failed!
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          Please check the workflow run for details.
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}